# Dev - namespace `dev`. Tag `dev-<sha>`.
replicaCount: 1

extraEnv:
  - name: APP_ENV
    value: dev

podAnnotations:
  environment: dev

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
